[platformio]
default_envs = node1

[env:node1]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DNODE_ID=1
monitor_speed = 115200
lib_deps = https://github.com/Fhilb/DW3000_Arduino.git

[env:node2]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DNODE_ID=2
monitor_speed = 115200
lib_deps = https://github.com/Fhilb/DW3000_Arduino.git

[env:node3]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DNODE_ID=3
monitor_speed = 115200
lib_deps = https://github.com/Fhilb/DW3000_Arduino.git

[env:node4]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DNODE_ID=4
monitor_speed = 115200
lib_deps = https://github.com/Fhilb/DW3000_Arduino.git
